# Generated by Django 3.2.9 on 2021-12-21 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'post site', 'verbose_name_plural': 'post sites'},
        ),
    ]
